- name: Scan de vulnérabilités
  hosts: Client1
  become: true
  tasks:
    - name: Ajout de la clé GPG du référentiel Metasploit
      apt_key:
        url: https://apt.metasploit.com/metasploit-framework.gpg.key

    - name: Ajout du référentiel Metasploit
      apt_repository:
        repo: 'deb https://apt.metasploit.com/ trusty main'
        state: present

    - name: Mise à jour de la liste des paquets disponibles
      apt:
        update_cache: yes

    - name: Installation des outils de sécurité courants
      apt:
        name: ['nmap', 'nikto', 'metasploit-framework', 'wireshark', 'tshark']

    - name: Exécution d'un test de vulnérabilité
      shell: nmap -sS -T4 -A -v -Pn > rapport_scan_nmap.txt {{ ansible_host }}

    - name: Recherche des mots de passe incorrects dans le journal d'authentification
      shell: grep -iE 'authentication failure' /var/log/auth.log > auth_failures.log || true
      changed_when: false

    - name: Récupération des événements d'échec d'authentification
      fetch:
        src: /home/ansible/auth_failures.log
        dest: ./auth_failures.log

    - name: Scan de vulnérabilité des applications web
      shell: nikto -h 192.168.10.133 -evasion 3 -Cgidirs /cgi-bin,/scripts > rapport_scan_nikto.txt {{ ansible_host }}

    - name: Récupération du fichier de journal nmap
      fetch:
        src: /home/ansible/rapport_scan_nmap.txt
        dest: ./nmap.log

    - name: Capture du trafic réseau avec Wireshark
      become: true
      shell: tcpdump -i ens33 -G 60 -W 1 -w rapport_wireshark.pcap
      args:
      executable: /bin/bash

    - name: Récupération du fichier de capture Wireshark
      fetch:
        src: /home/ansible/rapport_wireshark.pcap
        dest: ./wireshark.pcap

    - name: Génération du rapport des vulnérabilités détectées via Wireshark
      shell: tcpdump -r ./wireshark.pcap -Y "ssl.handshake.type==1 && ssl.handshake.certificate_length>0" -T fields -e ssl.handshake.extensions_server_name > rapport_vulns_wireshark.txt
      args:
        executable: /bin/bash

    - name: Récupération du fichier de journal nikto
      fetch:
        src: /home/ansible/rapport_scan_nikto.txt
        dest: ./nikto.log

    - name: Affichage du nombre de tentatives de mots de passe échoués
      shell: "grep -icE 'authentication failure' /var/log/auth.log"
      register: auth_failures_count
      changed_when: false

    - name: Affichage du nombre de tentatives de mots de passe échoués
      debug:
        msg: "Nombre de tentatives de mots de passe échoués : {{ auth_failures_count.stdout }}"

    - name: Génération d'un rapport des événements d'échec d'authentification
      shell: cat ./auth_failures.log >> rapport_auth_failures.txt
      args:
        executable: /bin/bash
 
